/*
 * Copyright (c) 2025 Portland State Aerospace Society
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "ers-pwm.h"

#include <zephyr/kernel.h>
#include <zephyr/device.h>
#include <zephyr/drivers/pwm.h>
#include <zephyr/logging/log.h>
#include <zephyr/shell/shell.h>
#include <zephyr/shell/shell_uart.h>

LOG_MODULE_REGISTER(pwm, LOG_LEVEL_INF);

static const struct pwm_dt_spec pwm_buzzer = PWM_DT_SPEC_GET(DT_ALIAS(buzzer));

#define MIN_PERIOD PWM_SEC(1U) / 128U
#define MAX_PERIOD PWM_SEC(1U)

static uint32_t max_period_fs;

struct k_thread pwm_thread_data;

K_THREAD_STACK_DEFINE(pwm_thread_stack, CONFIG_PWM_THREAD_STACK_SIZE);

#define PWM_NOTES_MAX_COUNT 16

// Structures for notes and patterns of notes

struct buzzer_note {
	uint32_t period;      // in scaled units of 1/Hz
	uint32_t duration_ms; // in milliseconds
};

struct audio_pattern {
	struct buzzer_note notes[PWM_NOTES_MAX_COUNT];
	// struct buzzer_note notes[];
	uint32_t repetitions; // times to repeat the pattern
	uint32_t rep_count;
	uint32_t last_note;
	uint32_t note_idx;
};

struct audio_pattern audio_pattern[] = {
	{
		.notes = {
			{ .period = 0, .duration_ms = 1000, },
		},
		.repetitions = 1,
		.rep_count = 0,
		.last_note = 1,
		.note_idx = 0,
	},
	{
		.notes = {
			{ .period = 2800000, .duration_ms = 220, },
			{ .period = 2500000, .duration_ms = 220, },
			{ .period = 2110000, .duration_ms = 220, },
			{ .period = 1700000, .duration_ms = 220, },
			{ .period = 1300000, .duration_ms = 220, },
		},
		.repetitions = 1,
		.rep_count = 0,
		.last_note = 4,
		.note_idx = 0,
	},
	// Lumidelic "Mandala"
	{
		.notes = {
			{ .period = 0, .duration_ms = 220, },
			{ .period = 2700000, .duration_ms = 220, },
			{ .period = 2170000, .duration_ms = 220, },
			{ .period = 2000000, .duration_ms = 220, },

			{ .period = 0, .duration_ms = 220, },
			{ .period = 1800000, .duration_ms = 440, },
			{ .period = 2700000, .duration_ms = 220, },
#if 1
			{ .period = 0, .duration_ms = 220, },
			{ .period = 2700000, .duration_ms = 220, },
			{ .period = 2170000, .duration_ms = 220, },
			{ .period = 2000000, .duration_ms = 220, },

			{ .period = 0, .duration_ms = 220, },
			{ .period = 1800000, .duration_ms = 440, },
			{ .period = 0, .duration_ms = 220, },
#endif // 0
		},
		.repetitions = 1,
		.rep_count = 0,
		.last_note = 14,
		.note_idx = 0,
	},
};

// Data types and variables for PWM module state

enum pwm_state {
	PWM_IDLE,
	PWM_PLAYING,
};

static enum pwm_state pwm_state_fs = PWM_IDLE;

static enum pwm_audio_pattern selected_pattern_fs = PWM_APP_SILENT;

//----------------------------------------------------------------------
// - SECTION - routines
//----------------------------------------------------------------------

static int32_t init_pwm_hardware(void)
{
	int32_t rc = 0;

	// LOG_INF("initializing PWM for device '%s'\n", pwm_buzzer.dev->name);

	if (!pwm_is_ready_dt(&pwm_buzzer)) {
		LOG_ERR("Error: PWM device %s is not ready\n",
		       pwm_buzzer.dev->name);
		return -ENODEV;
	}

	/*
	 * In case the default MAX_PERIOD value cannot be set for
	 * some PWM hardware, decrease its value until it can.
	 *
	 * Keep its value at least MIN_PERIOD * 4 to make sure
	 * the sample changes frequency at least once.
	 */
	// LOG_INF("Calibrating for channel %d...\n", pwm_buzzer.channel);
	max_period_fs = MAX_PERIOD;
	while (pwm_set_dt(&pwm_buzzer, max_period_fs, max_period_fs / 2U)) {
		max_period_fs /= 2U;
		if (max_period_fs < (4U * MIN_PERIOD)) {
			LOG_ERR("Error: PWM device "
			       "does not support a period at least %lu\n",
			       4U * MIN_PERIOD);
			return -ENOTSUP;
		}
	}

	LOG_INF("Done calibrating; maximum/minimum periods %u/%lu nsec\n",
	       max_period_fs, MIN_PERIOD);

	return rc;
}

/*
Using period 15625000
Using period 7812500   . . . 256
Using period 15625000  . . . 128
Using period 31250000   . . . 64
Using period 62500000   . . . 32
Using period 125000000  . . . 16
Using period 250000000   . . . 8
Using period 500000000   . . . 4
Using period 1000000000  . . . 2 Hertz
Using period 500000000

From ChibiOS ERS work, source file beep.c:

 16   // Sweeps through the speaker frequency range once a second from low to high
 17   // by changing the PWM period. At a PWM timer rate of 100khz the periods
 18   // correspond to:
 19   // - 28 -> ~3570Hz
 20   // - 25 ->  4000Hz
 21   // - 23 -> ~4350Hz
*/

/**
 * @brief Routine to play a note on the ERS buzzer.
 *
 * @param period
 * @param duty
 * @param period
 *
 * @retval 0 on success.
 * @return negative errno as generated by Zephyr's API.
 */

static int32_t play_note(const uint32_t period,
			const uint32_t duty,
			const uint32_t duration)
{
	// TODO [ ] Implement some modest, reasonable maximum duration.
	// TODO [ ] Consider adding a LOG_ERR() at the check point for rc.

	int32_t rc = pwm_set_dt(&pwm_buzzer, period, duty);
	if (rc < 0) {
		goto done;
	}
	k_msleep(duration);
	rc = pwm_set_dt(&pwm_buzzer, 0, 0);

done:
	return rc;
}

static int32_t play_pattern(void)
{
	int32_t rc = 0;


	// Obtain index to audio pattern:
	uint32_t pidx = selected_pattern_fs;

	// Obtain count of repetitions to play pattern, and running rep count:
	uint32_t repetitions = audio_pattern[pidx].repetitions;
	uint32_t reps_count = audio_pattern[pidx].rep_count;
	if (reps_count >= repetitions) {
		// When we've played all reps of the pattern, set module state to idle:
		pwm_state_fs = PWM_IDLE;
		goto done;
	}

	// Obtain index to current note to play in pattern:
	uint32_t nidx = audio_pattern[pidx].note_idx;

	// When we've played all the notes of a pattern, increment the rep count,
	// and reset the note index:
	if (nidx >= audio_pattern[pidx].last_note) {
		audio_pattern[pidx].rep_count++;
		audio_pattern[pidx].note_idx = 0;
	}

	// Obtain the note's period and duration:
	uint32_t period = audio_pattern[pidx].notes[nidx].period;
	uint32_t duration = audio_pattern[pidx].notes[nidx].duration_ms;

	rc = play_note(period, period / 2, duration);
	audio_pattern[pidx].note_idx++;

#if 1
	const struct shell *shell;
	shell = shell_backend_uart_get_ptr();
	__ASSERT(shell != NULL, "Failed to get shell backend.");
#if 0
	shell_print(shell, "- DEV 0822 - Current audio pattern has %d notes",
			audio_pattern[pidx].last_note);
#endif // 0
#endif

done:
	return rc;
}

// Public API, by which caller starts an audio pattern playing:

int32_t pwm_play_pattern(enum pwm_audio_pattern pattern)
{
	int32_t rc = 0;

	switch (pattern) {
	case PWM_APP_SILENT:
		pwm_state_fs = PWM_IDLE;
		break;
	case PWM_APP_BANNER_PATTERN:
		selected_pattern_fs = PWM_APP_BANNER_PATTERN;
		pwm_state_fs = PWM_PLAYING;
		break;
	case PWM_APP_15_NOTES:
		selected_pattern_fs = PWM_APP_15_NOTES;
		pwm_state_fs = PWM_PLAYING;
		break;
	case PWM_APP_HEARTBEAT:
		selected_pattern_fs = PWM_APP_HEARTBEAT;
		pwm_state_fs = PWM_PLAYING;
		break;
	case PWM_ROCKET_READY:
		selected_pattern_fs = PWM_ROCKET_READY;
		pwm_state_fs = PWM_PLAYING;
		break;
	default:
		LOG_ERR("Got unknown audio pattern request %d", pattern);
		rc = -EINVAL;
		goto done;
	}

done:
	return rc;
}

void pwm_thread_entry(void *arg1, void *arg2, void *arg3)
{
	ARG_UNUSED(arg1);
	ARG_UNUSED(arg2);
	ARG_UNUSED(arg3);

	int32_t rc = 0;

	while (1) {
		if (pwm_state_fs == PWM_PLAYING) {
			rc = play_pattern();
			if (rc < 0) {
				LOG_ERR("Failed to play audio pattern, err %d", rc);
			}
			k_msleep(10);
		} else {
			// TODO [ ] Create symbol for PWM thread sleep period
			k_msleep(750);
		}
	}
}

int32_t pwm_init(void)
{
	int32_t rc = init_pwm_hardware();
	if (rc < 0) {
		LOG_ERR("Failed to initialize PWM peripheral, err %d", rc);
		goto done;
	}

	k_tid_t pwm_tid = k_thread_create(&pwm_thread_data,
					pwm_thread_stack,
					K_THREAD_STACK_SIZEOF(pwm_thread_stack),
					pwm_thread_entry,
					NULL, NULL, NULL,
					CONFIG_PWM_THREAD_PRIORITY,
					0, K_NO_WAIT);

	k_thread_name_set(pwm_tid, "pwm_thread");

	if (!pwm_tid) {
		LOG_ERR("ERROR spawning PWM thread\n");
	}

// For shell pointer use see:
// https://blog.mbedded.ninja/programming/operating-systems/zephyr/shell/
	const struct shell *shell;
	shell = shell_backend_uart_get_ptr();
	__ASSERT(shell != NULL, "Failed to get shell backend.");
	shell_print(shell, "PWM module started, %d buzzer patterns defined",
			ARRAY_SIZE(audio_pattern));

done:
	return rc;
}
