# PSAS Electromechanical Recovery System (ERS) firmware

# C library
CONFIG_NEWLIB_LIBC=y

# On chip peripherals
CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_DAC=y
CONFIG_PWM=y

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_MAIN_STACK_SIZE=2048

# ERS application threads
CONFIG_CAN_RX_THREAD_PRIORITY=2
CONFIG_ADC_THREAD_PRIORITY=3
CONFIG_GPIO_THREAD_PRIORITY=4
CONFIG_ARBITER_THREAD_PRIORITY=5

CONFIG_ADC_THREAD_STACK_SIZE=512
CONFIG_ARBITER_THREAD_STACK_SIZE=1024
CONFIG_CAN_RX_THREAD_STACK_SIZE=1536
CONFIG_GPIO_THREAD_STACK_SIZE=512

# CAN bus related
CONFIG_POLL=y
CONFIG_CAN=y
CONFIG_CAN_FD_MODE=y
CONFIG_CAN_INIT_PRIORITY=80
CONFIG_CAN_MAX_FILTER=5

CONFIG_SHELL=y
CONFIG_CAN_SHELL=y
CONFIG_DEVICE_SHELL=y

CONFIG_STATS=y
CONFIG_STATS_NAMES=y
CONFIG_STATS_SHELL=y
CONFIG_CAN_STATS=y

CONFIG_LOOPBACK_MODE=n
CONFIG_SAMPLE_CAN_COUNTER_LOG_LEVEL_INF=y
CONFIG_CAN_LOG_LEVEL_ERR=y

# In support of Zephyr settings submodule (credit Pete S.):
CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

# Zephyr settings submodule, for persistent data storage
CONFIG_SETTINGS=y
CONFIG_SETTINGS_RUNTIME=y

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FCB=y
CONFIG_SETTINGS_FCB=y

# Zephyr thread introspection
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_NAME=y

CONFIG_LOG=y
